// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torch2trt/converters/interpolate/interpolate.proto

#ifndef PROTOBUF_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto__INCLUDED
#define PROTOBUF_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace torch2trt {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();
void protobuf_AssignDesc_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();
void protobuf_ShutdownFile_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();

class interpolate_Message;

enum DataTypeMessage {
  kFloat = 0,
  kHalf = 1,
  kInt8 = 2,
  kInt32 = 3,
  DataTypeMessage_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DataTypeMessage_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DataTypeMessage_IsValid(int value);
const DataTypeMessage DataTypeMessage_MIN = kFloat;
const DataTypeMessage DataTypeMessage_MAX = kInt32;
const int DataTypeMessage_ARRAYSIZE = DataTypeMessage_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataTypeMessage_descriptor();
inline const ::std::string& DataTypeMessage_Name(DataTypeMessage value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataTypeMessage_descriptor(), value);
}
inline bool DataTypeMessage_Parse(
    const ::std::string& name, DataTypeMessage* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataTypeMessage>(
    DataTypeMessage_descriptor(), name, value);
}
// ===================================================================

class interpolate_Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:torch2trt.interpolate_Message) */ {
 public:
  interpolate_Message();
  virtual ~interpolate_Message();

  interpolate_Message(const interpolate_Message& from);

  inline interpolate_Message& operator=(const interpolate_Message& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const interpolate_Message& default_instance();

  void Swap(interpolate_Message* other);

  // implements Message ----------------------------------------------

  inline interpolate_Message* New() const { return New(NULL); }

  interpolate_Message* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const interpolate_Message& from);
  void MergeFrom(const interpolate_Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(interpolate_Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 size = 1;
  int size_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 1;
  ::google::protobuf::int64 size(int index) const;
  void set_size(int index, ::google::protobuf::int64 value);
  void add_size(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      size() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_size();

  // optional string mode = 2;
  void clear_mode();
  static const int kModeFieldNumber = 2;
  const ::std::string& mode() const;
  void set_mode(const ::std::string& value);
  void set_mode(const char* value);
  void set_mode(const char* value, size_t size);
  ::std::string* mutable_mode();
  ::std::string* release_mode();
  void set_allocated_mode(::std::string* mode);

  // optional bool align_corners = 3;
  void clear_align_corners();
  static const int kAlignCornersFieldNumber = 3;
  bool align_corners() const;
  void set_align_corners(bool value);

  // optional .torch2trt.DataTypeMessage dtype = 4;
  void clear_dtype();
  static const int kDtypeFieldNumber = 4;
  ::torch2trt::DataTypeMessage dtype() const;
  void set_dtype(::torch2trt::DataTypeMessage value);

  // repeated int64 input_size = 5;
  int input_size_size() const;
  void clear_input_size();
  static const int kInputSizeFieldNumber = 5;
  ::google::protobuf::int64 input_size(int index) const;
  void set_input_size(int index, ::google::protobuf::int64 value);
  void add_input_size(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      input_size() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_input_size();

  // repeated int64 output_size = 6;
  int output_size_size() const;
  void clear_output_size();
  static const int kOutputSizeFieldNumber = 6;
  ::google::protobuf::int64 output_size(int index) const;
  void set_output_size(int index, ::google::protobuf::int64 value);
  void add_output_size(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      output_size() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_output_size();

  // @@protoc_insertion_point(class_scope:torch2trt.interpolate_Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > size_;
  mutable int _size_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr mode_;
  bool align_corners_;
  int dtype_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > input_size_;
  mutable int _input_size_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > output_size_;
  mutable int _output_size_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();
  friend void protobuf_AssignDesc_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();
  friend void protobuf_ShutdownFile_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto();

  void InitAsDefaultInstance();
  static interpolate_Message* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// interpolate_Message

// repeated int64 size = 1;
inline int interpolate_Message::size_size() const {
  return size_.size();
}
inline void interpolate_Message::clear_size() {
  size_.Clear();
}
inline ::google::protobuf::int64 interpolate_Message::size(int index) const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.size)
  return size_.Get(index);
}
inline void interpolate_Message::set_size(int index, ::google::protobuf::int64 value) {
  size_.Set(index, value);
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.size)
}
inline void interpolate_Message::add_size(::google::protobuf::int64 value) {
  size_.Add(value);
  // @@protoc_insertion_point(field_add:torch2trt.interpolate_Message.size)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
interpolate_Message::size() const {
  // @@protoc_insertion_point(field_list:torch2trt.interpolate_Message.size)
  return size_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
interpolate_Message::mutable_size() {
  // @@protoc_insertion_point(field_mutable_list:torch2trt.interpolate_Message.size)
  return &size_;
}

// optional string mode = 2;
inline void interpolate_Message::clear_mode() {
  mode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& interpolate_Message::mode() const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.mode)
  return mode_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void interpolate_Message::set_mode(const ::std::string& value) {
  
  mode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.mode)
}
inline void interpolate_Message::set_mode(const char* value) {
  
  mode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:torch2trt.interpolate_Message.mode)
}
inline void interpolate_Message::set_mode(const char* value, size_t size) {
  
  mode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:torch2trt.interpolate_Message.mode)
}
inline ::std::string* interpolate_Message::mutable_mode() {
  
  // @@protoc_insertion_point(field_mutable:torch2trt.interpolate_Message.mode)
  return mode_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* interpolate_Message::release_mode() {
  // @@protoc_insertion_point(field_release:torch2trt.interpolate_Message.mode)
  
  return mode_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void interpolate_Message::set_allocated_mode(::std::string* mode) {
  if (mode != NULL) {
    
  } else {
    
  }
  mode_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mode);
  // @@protoc_insertion_point(field_set_allocated:torch2trt.interpolate_Message.mode)
}

// optional bool align_corners = 3;
inline void interpolate_Message::clear_align_corners() {
  align_corners_ = false;
}
inline bool interpolate_Message::align_corners() const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.align_corners)
  return align_corners_;
}
inline void interpolate_Message::set_align_corners(bool value) {
  
  align_corners_ = value;
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.align_corners)
}

// optional .torch2trt.DataTypeMessage dtype = 4;
inline void interpolate_Message::clear_dtype() {
  dtype_ = 0;
}
inline ::torch2trt::DataTypeMessage interpolate_Message::dtype() const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.dtype)
  return static_cast< ::torch2trt::DataTypeMessage >(dtype_);
}
inline void interpolate_Message::set_dtype(::torch2trt::DataTypeMessage value) {
  
  dtype_ = value;
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.dtype)
}

// repeated int64 input_size = 5;
inline int interpolate_Message::input_size_size() const {
  return input_size_.size();
}
inline void interpolate_Message::clear_input_size() {
  input_size_.Clear();
}
inline ::google::protobuf::int64 interpolate_Message::input_size(int index) const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.input_size)
  return input_size_.Get(index);
}
inline void interpolate_Message::set_input_size(int index, ::google::protobuf::int64 value) {
  input_size_.Set(index, value);
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.input_size)
}
inline void interpolate_Message::add_input_size(::google::protobuf::int64 value) {
  input_size_.Add(value);
  // @@protoc_insertion_point(field_add:torch2trt.interpolate_Message.input_size)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
interpolate_Message::input_size() const {
  // @@protoc_insertion_point(field_list:torch2trt.interpolate_Message.input_size)
  return input_size_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
interpolate_Message::mutable_input_size() {
  // @@protoc_insertion_point(field_mutable_list:torch2trt.interpolate_Message.input_size)
  return &input_size_;
}

// repeated int64 output_size = 6;
inline int interpolate_Message::output_size_size() const {
  return output_size_.size();
}
inline void interpolate_Message::clear_output_size() {
  output_size_.Clear();
}
inline ::google::protobuf::int64 interpolate_Message::output_size(int index) const {
  // @@protoc_insertion_point(field_get:torch2trt.interpolate_Message.output_size)
  return output_size_.Get(index);
}
inline void interpolate_Message::set_output_size(int index, ::google::protobuf::int64 value) {
  output_size_.Set(index, value);
  // @@protoc_insertion_point(field_set:torch2trt.interpolate_Message.output_size)
}
inline void interpolate_Message::add_output_size(::google::protobuf::int64 value) {
  output_size_.Add(value);
  // @@protoc_insertion_point(field_add:torch2trt.interpolate_Message.output_size)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
interpolate_Message::output_size() const {
  // @@protoc_insertion_point(field_list:torch2trt.interpolate_Message.output_size)
  return output_size_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
interpolate_Message::mutable_output_size() {
  // @@protoc_insertion_point(field_mutable_list:torch2trt.interpolate_Message.output_size)
  return &output_size_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace torch2trt

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::torch2trt::DataTypeMessage> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::torch2trt::DataTypeMessage>() {
  return ::torch2trt::DataTypeMessage_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_torch2trt_2fconverters_2finterpolate_2finterpolate_2eproto__INCLUDED
