# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torch2trt/converters/interpolate/interpolate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='torch2trt/converters/interpolate/interpolate.proto',
  package='torch2trt',
  syntax='proto3',
  serialized_pb=_b('\n2torch2trt/converters/interpolate/interpolate.proto\x12\ttorch2trt\"\x9c\x01\n\x13interpolate_Message\x12\x0c\n\x04size\x18\x01 \x03(\x03\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x15\n\ralign_corners\x18\x03 \x01(\x08\x12)\n\x05\x64type\x18\x04 \x01(\x0e\x32\x1a.torch2trt.DataTypeMessage\x12\x12\n\ninput_size\x18\x05 \x03(\x03\x12\x13\n\x0boutput_size\x18\x06 \x03(\x03*?\n\x0f\x44\x61taTypeMessage\x12\n\n\x06kFloat\x10\x00\x12\t\n\x05kHalf\x10\x01\x12\t\n\x05kInt8\x10\x02\x12\n\n\x06kInt32\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DATATYPEMESSAGE = _descriptor.EnumDescriptor(
  name='DataTypeMessage',
  full_name='torch2trt.DataTypeMessage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kFloat', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kHalf', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInt8', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInt32', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=224,
  serialized_end=287,
)
_sym_db.RegisterEnumDescriptor(_DATATYPEMESSAGE)

DataTypeMessage = enum_type_wrapper.EnumTypeWrapper(_DATATYPEMESSAGE)
kFloat = 0
kHalf = 1
kInt8 = 2
kInt32 = 3



_INTERPOLATE_MESSAGE = _descriptor.Descriptor(
  name='interpolate_Message',
  full_name='torch2trt.interpolate_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='torch2trt.interpolate_Message.size', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='torch2trt.interpolate_Message.mode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='align_corners', full_name='torch2trt.interpolate_Message.align_corners', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='torch2trt.interpolate_Message.dtype', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_size', full_name='torch2trt.interpolate_Message.input_size', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_size', full_name='torch2trt.interpolate_Message.output_size', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=222,
)

_INTERPOLATE_MESSAGE.fields_by_name['dtype'].enum_type = _DATATYPEMESSAGE
DESCRIPTOR.message_types_by_name['interpolate_Message'] = _INTERPOLATE_MESSAGE
DESCRIPTOR.enum_types_by_name['DataTypeMessage'] = _DATATYPEMESSAGE

interpolate_Message = _reflection.GeneratedProtocolMessageType('interpolate_Message', (_message.Message,), dict(
  DESCRIPTOR = _INTERPOLATE_MESSAGE,
  __module__ = 'torch2trt.converters.interpolate.interpolate_pb2'
  # @@protoc_insertion_point(class_scope:torch2trt.interpolate_Message)
  ))
_sym_db.RegisterMessage(interpolate_Message)


# @@protoc_insertion_point(module_scope)
